spring:
  application:
    name: spring-ai-demo

  ai:
    openai:
      api-key: OPEN_AI_API_KEY
      chat:
        options:
          model: ai/mistral
          temperature: 0.7
          maxTokens: 2048 # System-wide default for max tokens
      base-url: http://localhost:12434/engines
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/schema/h2-db.sql

  datasource:
    url: jdbc:h2:file:~/chatmemory;AUTO_SERVER=true # File allows for chat memory to be stored on a file on your system
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

app:
  config:
    ai:
      prompt-templates:
        system-templates:
          insurance-company-template: classpath:/prompttemplates/systemprompts/insurance-company-template.st
          estate-agent-search-template: classpath:/prompttemplates/systemprompts/estate-agent-search-template.st
          fruit-tree-location-template: classpath:/prompttemplates/systemprompts/fruit-tree-location-template.st
          fruit-tree-info-template: classpath:/prompttemplates/systemprompts/fruit-tree-info-template.st
        user-templates:
          email-template: classpath:/prompttemplates/userprompts/email-prompt-template.st

logging:
  level:
    org:
      springframework:
        ai: DEBUG